#!/usr/bin/env bash
# ============================================================
# check-coverage.sh
# BofA Devin Skill — Jest coverage runner for all services.
# Outputs a Markdown coverage table to coverage/summary.md.
#
# Usage: ./.devin/skills/check-coverage.sh
# Called by: test-coverage.md weekly playbook, Phase 6 guardrail
#
# Exit codes:
#   0 — All compliance paths meet 80% threshold
#   1 — One or more compliance paths below threshold
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COVERAGE_DIR="$REPO_ROOT/coverage"
SUMMARY_FILE="$COVERAGE_DIR/summary.md"

mkdir -p "$COVERAGE_DIR"

# 12 services to check
declare -A SERVICES=(
  ["retail-banking-portal/auth"]="apps/retail-banking-portal/src/app/auth"
  ["retail-banking-portal/transactions"]="apps/retail-banking-portal/src/app/transactions"
  ["retail-banking-portal/analytics"]="apps/retail-banking-portal/src/app/analytics"
  ["retail-banking-portal/dashboard"]="apps/retail-banking-portal/src/app/dashboard"
  ["corporate-dashboard/auth"]="apps/corporate-dashboard/src/app/auth"
  ["corporate-dashboard/core"]="apps/corporate-dashboard/src/app/core"
  ["mobile-api-gateway/auth"]="apps/mobile-api-gateway/src/app/auth"
  ["mobile-api-gateway/gateway"]="apps/mobile-api-gateway/src/app/gateway"
  ["shared-ui/button"]="libs/shared-ui/src/lib/button"
  ["shared-ui/data-table"]="libs/shared-ui/src/lib/data-table"
  ["shared-data-access/banking-api"]="libs/shared-data-access/src/lib/api"
  ["shared-data-access/fraud"]="libs/shared-data-access/src/lib/api"
)

# Compliance paths requiring 80%
COMPLIANCE_PATHS=(
  "retail-banking-portal/auth"
  "retail-banking-portal/transactions"
  "corporate-dashboard/auth"
  "mobile-api-gateway/auth"
  "shared-data-access/banking-api"
  "shared-data-access/fraud"
)

PASS_COUNT=0
FAIL_COUNT=0
BELOW_THRESHOLD=()

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

echo ""
echo -e "${BLUE}╔════════════════════════════════════════════╗${RESET}"
echo -e "${BLUE}║   BofA Jest Coverage Report                ║${RESET}"
echo -e "${BLUE}╚════════════════════════════════════════════╝${RESET}"
echo ""

# Initialize Markdown report
cat > "$SUMMARY_FILE" << 'MDEOF'
# BofA Test Coverage Report

Generated by `check-coverage.sh` — BofA Devin Skill

| Service | Statements | Branches | Functions | Lines | Threshold | Status |
|---|---|---|---|---|---|---|
MDEOF

for SERVICE_KEY in "${!SERVICES[@]}"; do
  SERVICE_PATH="${SERVICES[$SERVICE_KEY]}"

  IS_COMPLIANCE=false
  for COMPLIANCE_PATH in "${COMPLIANCE_PATHS[@]}"; do
    if [[ "$SERVICE_KEY" == "$COMPLIANCE_PATH" ]]; then
      IS_COMPLIANCE=true
      break
    fi
  done

  THRESHOLD=60
  if [[ "$IS_COMPLIANCE" == "true" ]]; then
    THRESHOLD=80
  fi

  echo -e "  ${BLUE}▶ $SERVICE_KEY${RESET} (threshold: ${THRESHOLD}%)"

  COVERAGE_JSON="$COVERAGE_DIR/$SERVICE_KEY/coverage-summary.json"
  mkdir -p "$COVERAGE_DIR/$SERVICE_KEY"

  # Run Jest scoped to this service path
  npx jest \
    --testPathPattern="$SERVICE_PATH" \
    --coverage \
    --coverageDirectory="$COVERAGE_DIR/$SERVICE_KEY" \
    --coverageReporters=json-summary \
    --passWithNoTests \
    --silent 2>/dev/null || true

  if [[ -f "$COVERAGE_JSON" ]]; then
    STATEMENTS=$(python3 -c "import json; d=json.load(open('$COVERAGE_JSON')); print(round(d['total']['statements']['pct']))" 2>/dev/null || echo "0")
    BRANCHES=$(python3 -c "import json; d=json.load(open('$COVERAGE_JSON')); print(round(d['total']['branches']['pct']))" 2>/dev/null || echo "0")
    FUNCTIONS=$(python3 -c "import json; d=json.load(open('$COVERAGE_JSON')); print(round(d['total']['functions']['pct']))" 2>/dev/null || echo "0")
    LINES=$(python3 -c "import json; d=json.load(open('$COVERAGE_JSON')); print(round(d['total']['lines']['pct']))" 2>/dev/null || echo "0")
  else
    STATEMENTS=0; BRANCHES=0; FUNCTIONS=0; LINES=0
  fi

  MIN_COVERAGE=$((BRANCHES < STATEMENTS ? BRANCHES : STATEMENTS))
  MIN_COVERAGE=$((MIN_COVERAGE < FUNCTIONS ? MIN_COVERAGE : FUNCTIONS))
  MIN_COVERAGE=$((MIN_COVERAGE < LINES ? MIN_COVERAGE : LINES))

  if [[ "$MIN_COVERAGE" -ge "$THRESHOLD" ]]; then
    STATUS="✅ PASS"
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "    ${GREEN}✓ PASS${RESET} — min: ${MIN_COVERAGE}% (required: ${THRESHOLD}%)"
  else
    STATUS="❌ FAIL"
    FAIL_COUNT=$((FAIL_COUNT + 1))
    BELOW_THRESHOLD+=("$SERVICE_KEY (min: ${MIN_COVERAGE}%, required: ${THRESHOLD}%)")
    echo -e "    ${RED}✗ FAIL${RESET} — min: ${MIN_COVERAGE}% (required: ${THRESHOLD}%)"
  fi

  THRESHOLD_LABEL="${THRESHOLD}%"
  if [[ "$IS_COMPLIANCE" == "true" ]]; then
    THRESHOLD_LABEL="**${THRESHOLD}% (compliance)**"
  fi

  echo "| \`$SERVICE_KEY\` | ${STATEMENTS}% | ${BRANCHES}% | ${FUNCTIONS}% | ${LINES}% | ${THRESHOLD_LABEL} | ${STATUS} |" >> "$SUMMARY_FILE"
done

# Append summary footer
{
  echo ""
  echo "---"
  echo ""
  echo "## Summary"
  echo ""
  echo "- **Services checked:** ${#SERVICES[@]}"
  echo "- **Passed:** $PASS_COUNT"
  echo "- **Failed:** $FAIL_COUNT"
  echo ""
} >> "$SUMMARY_FILE"

if [[ ${#BELOW_THRESHOLD[@]} -gt 0 ]]; then
  {
    echo "### Services Below Threshold"
    echo ""
    for ITEM in "${BELOW_THRESHOLD[@]}"; do
      echo "- ❌ \`$ITEM\`"
    done
    echo ""
    echo "_Automated Devin sessions will be opened per \`test-coverage.md\` playbook._"
  } >> "$SUMMARY_FILE"
fi

echo ""
echo -e "${YELLOW}Coverage report → ${SUMMARY_FILE}${RESET}"
echo ""

if [[ "$FAIL_COUNT" -gt 0 ]]; then
  echo -e "${RED}╔═══════════════════════════════════════════════════════════════╗${RESET}"
  echo -e "${RED}║  COVERAGE CHECK FAILED: $FAIL_COUNT service(s) below threshold.        ║${RESET}"
  echo -e "${RED}║  Parallel Devin sessions will be opened per test-coverage.md ║${RESET}"
  echo -e "${RED}╚═══════════════════════════════════════════════════════════════╝${RESET}"
  for ITEM in "${BELOW_THRESHOLD[@]}"; do
    echo -e "  ${RED}✗ $ITEM${RESET}"
  done
  exit 1
else
  echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${RESET}"
  echo -e "${GREEN}║  ALL COVERAGE CHECKS PASSED ✓                               ║${RESET}"
  echo -e "${GREEN}║  All compliance paths meet the 80% threshold.               ║${RESET}"
  echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${RESET}"
  exit 0
fi
